version: '3.3'

services:
  postgres:
    image: postgres:9.5
    ports:
      - 54321:5432
    environment:
      - POSTGRES_USER=hurumapdata
      - POSTGRES_PASSWORD=hurumapdata
      - POSTGRES_DB=hurumapdata
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
  graphql:
    image: node:12.4.0
    depends_on:
      - postgres
    command: npx \
      postgraphile \
      --subscriptions \
      --watch \
      --dynamic-json \
      --no-setof-functions-contain-nulls
      --no-ignore-rbac
      --no-ignore-indexes
      --show-error-stack=json
      --extended-errors hint,detail,errcode
      --append-plugins @graphile-contrib/pg-simplify-inflector
      --export-schema-graphql schema.graphql
      --graphiql "/"
      --enhance-graphiq
      --allow-explain
      --enable-query-batching
      --legacy-relations omit
      --connection postgres://hurumapdata:hurumapdata@postgres:54321/hurumapdata
      --schema public
