DROP TABLE IF EXISTS public.pesayetu_office_of_the_governor_county_administration_hy_2019_20;

DELETE FROM public.sources where table_name = 'allPesayetuOfficeOfTheGovernorCountyAdministrationHy201920S';