DROP TABLE IF EXISTS public.pesayetu_edu_youth_Affairs_Sports_Culture_Social_Services_hy_2019_20;

DELETE FROM public.sources where table_name = 'allPesayetuEduYouthAffairsSportsCultureSocialServicesHy201920S';